language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "Z/ALIJcdoMOTMyVjWk35uN4ZbVC3P/9eNecQ4iaPdkJRUByJww7LqKLxK8ml9Ac0ytD+Zue1LJLy1tyoEAY4dGBZjqjaDX3gW9AYM+R0687RcFo6sWQLqx8iZJuMGm9xgeZOEATbu6cWcdk3GeSe4SMKZaech1FiWkX1+jSDs4Rk15lOmOciYy+gwBmcjwxmb6HHu9tKHFuRc6mBfFjcXnqDTdFjjJCXlzjIJaz/sUXBmYFLDJxLsVnzgIe5c1gK8bOvWQBNh+GIHmZ3Qb9GWOeNOar06xRzsMSMFpA9y5Qk/r4C4d/pt38Zrero4d/Ww+MUa3NZVAeNCbylYVpEwmTra/oJA+y3On4xMqqTHXhaDvwGM9+eg2Qz11GAA2Aoic1QRyh/2NN8eUDZ6eBNz3lzTUhVMP+uZfjRLdrfAkU39znVh9VsbJ0DJG1Q2sDQ7+irGqSpdbC0dYZ15R7ilO8HaDgLJxxt7fqgD0NTWmuF63sjxjY58zDNk/dItgIQsyuE+atYgMF0SU5LaMyFinymURlgNEF8Es3WFX12KQY6K0yWMq4nUxWoMs5H7LesbXIS/mVHP5OO848hkAikmui554npWz3SmSFOvcxfn1hVBmZhlONh4vqt1yJXkMg6QYLKqm0spDZnoL/UP9bdv9v3thu95es1IiSaV03hCD0="

jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

branches:
  except:
  - gh-pages
